// Generated by scripts/generate-suite-protocol.mjs. Do not edit by hand.

#![allow(dead_code)]

pub const SUITE_DISCOVERY_SCHEMA_VERSION: u8 = 1;
pub const PULSE_RECORDING_INTAKE_FILE: &str = "pulse-recording-intake.json";
pub const MARKER_CONTRACT_NAME: &str = "vaexcore.studio.marker.v1";
pub const MARKER_CONTRACT_SCHEMA_VERSION: u8 = 1;
pub const STUDIO_APP_ID: &str = "vaexcore-studio";
pub const PULSE_APP_ID: &str = "vaexcore-pulse";
pub const CONSOLE_APP_ID: &str = "vaexcore-console";
pub const VAEXCORE_SUITE_APPS: &[&str] = &["vaexcore studio", "vaexcore pulse", "vaexcore console"];

#[derive(Clone, Copy)]
pub struct SuiteAppDefinition {
    pub app_id: &'static str,
    pub app_name: &'static str,
    pub launch_name: &'static str,
    pub bundle_identifier: &'static str,
    pub discovery_file: &'static str,
    pub health_endpoint: &'static str,
}

pub const SUITE_APP_DEFINITIONS: &[SuiteAppDefinition] = &[
    SuiteAppDefinition {
        app_id: "vaexcore-studio",
        app_name: "vaexcore studio",
        launch_name: "vaexcore studio",
        bundle_identifier: "com.vaexcore.studio",
        discovery_file: "vaexcore-studio.json",
        health_endpoint: "http://127.0.0.1:51287/health",
    },
    SuiteAppDefinition {
        app_id: "vaexcore-pulse",
        app_name: "vaexcore pulse",
        launch_name: "vaexcore pulse",
        bundle_identifier: "com.vaexil.vaexcore.pulse",
        discovery_file: "vaexcore-pulse.json",
        health_endpoint: "http://127.0.0.1:4010/health",
    },
    SuiteAppDefinition {
        app_id: "vaexcore-console",
        app_name: "vaexcore console",
        launch_name: "vaexcore console",
        bundle_identifier: "com.vaexil.vaexcore.console",
        discovery_file: "vaexcore-console.json",
        health_endpoint: "http://127.0.0.1:3434/api/status",
    },
];
